# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 15:27
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoZone',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(default='General', max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('course_count', models.IntegerField(blank=True, null=True)),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('org_type', models.CharField(blank=True, max_length=255)),
                ('github_fork', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('course_type', models.CharField(choices=[('MOOC', 'MOOC'), ('SPOC', 'SPOC'), ('Both', 'Both'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('registered_user_count', models.IntegerField(blank=True, null=True)),
                ('active_learner_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteGeoZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.GeoZone')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Language')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='geography',
            field=models.ManyToManyField(blank=True, through='sites.SiteGeoZone', to='sites.GeoZone'),
        ),
        migrations.AddField(
            model_name='site',
            name='language',
            field=models.ManyToManyField(blank=True, through='sites.SiteLanguage', to='sites.Language'),
        ),
    ]
