# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='course_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
