# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20160606_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
