# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 15:46
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20160622_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
