# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20160606_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='course_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='language',
            field=models.ManyToManyField(blank=True, through='sites.SiteLanguage', to='sites.Language'),
        ),
    ]
