# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20160610_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='course_count',
            field=models.IntegerField(),
        ),
    ]
