# Generated by Django 1.9.5 on 2016-06-27 17:43
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20160622_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='last_checked',
        ),
        migrations.AlterField(
            model_name='site',
            name='active_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
