# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20160610_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='course_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
