# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20160610_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
