# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_site_is_private_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('access_date', models.DateField(blank=True, default=None, null=True)),
                ('filename', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('access_count', models.IntegerField(blank=True, default=None, null=True)),
                ('create_dt', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='FilenameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accesslogaggregate',
            unique_together=set([('domain', 'access_date', 'filename')]),
        ),
    ]
