# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20160613_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='last_checked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
