# Generated by Django 1.9.5 on 2018-02-04 18:45
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_site_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_count', models.IntegerField(blank=True, null=True)),
                ('active_start_date', models.DateTimeField(default=datetime.datetime.now, unique=True)),
                ('active_end_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
