# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-07 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_site_is_gone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geozone',
            options={'ordering': ['geozone_name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language_name']},
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='language',
            name='name',
        ),
        migrations.AddField(
            model_name='geozone',
            name='geozone_name',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='language',
            name='language_name',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
