# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-02 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_site_is_gone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geozone',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
