# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-02 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_auto_20180802_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['lang_name']},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='lang_name',
        ),
    ]
