# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-02 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_auto_20180802_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geozone',
            options={'ordering': ['geo_name']},
        ),
        migrations.RenameField(
            model_name='geozone',
            old_name='name',
            new_name='geo_name',
        ),
    ]
