# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-02 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_auto_20180802_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geozone',
            options={'ordering': ['geozone_name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language_name']},
        ),
        migrations.RenameField(
            model_name='geozone',
            old_name='geo_name',
            new_name='geozone_name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name',
            new_name='language_name',
        ),
    ]
