# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-03 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_auto_20180802_2023'),
        ('sites', '0013_auto_20180802_2254'),
    ]

    operations = [
    ]
